// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package config

import (
	"time"
)

type Site struct {
	DbName     string    `json:"dbName"`
	Link       string    `json:"link"`
	UpdateDate time.Time `json:"updateDate"`
	AutoUpdate bool      `json:"autoUpdate"`
	Enabled    bool      `json:"enabled"`
}
